[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hinglish"
version = "1.0.0"
description = "A Python-compatible programming language interface using Hinglish syntax."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Neeraj Yadav", email = "neerajbhaiya1508@gmail.com" },
]
keywords = [
    "hinglish",
    "programming-language",
    "compiler",
    "transpiler",
    "python",
    "hindi",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Compilers",
    "Topic :: Software Development :: Interpreters",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "wheel",
]

[project.scripts]
hinglish = "hinglish.cli:main"

[project.urls]
Homepage = "https://github.com/NeerajYadav-coder/Hinglish_programming_language."
Repository = "https://github.com/NeerajYadav-coder/Hinglish_programming_language."

[tool.setuptools.packages.find]
where = ["."]
include = ["hinglish*"]
exclude = ["tests*", "examples*", "docs*"]
